name: boilerplate-application-melos

packages:
  - packages/api_client
  - packages/app_core
  - packages/app_ui
  - packages/app_translations

scripts:
  analyze:
    run: |
      melos exec -c 5 -- \
        dart analyze . --fatal-infos

  build-runner:
    description: Generate environment configuration, Routes files and other code generation
    packageFilters:
      flutter: true
      dirExists: lib
      scope: app_core
    run: melos exec dart run build_runner clean && melos exec dart run build_runner build -d

  asset-gen:
    description: Generate assets
    packageFilters:
      flutter: true
      dirExists: lib
      scope: app_ui
    run: melos exec dart run build_runner build -d

  locale-gen:
    description: Generate localization
    packageFilters:
      flutter: true
      dirExists: lib
      scope: app_translations
    exec: dart run slang

  build-apk:
    description: Builds the APK File
    packageFilters:
      flutter: true
      dirExists: lib
      scope: app_core
    exec: flutter build apk -t lib/main_development.dart

  format:
    description: Formats the files
    exec: dart format . --line-length 100
