name: boilerplate-application-melos

packages:
  - packages/**
  - apps/**

scripts:
  analyze:
    description: Analyze all Dart & Flutter packages
    run: dart analyze . --fatal-infos
    exec:
      concurrency: 10

  build-runner:
    description: Generate environment config, routes & code
    packageFilters:
      flutter: true
      scope: app_core
    run: |
      dart run build_runner clean
      dart run build_runner build --delete-conflicting-outputs

  asset-gen:
    description: Generate assets
    packageFilters:
      flutter: true
      scope: app_ui
    run: dart run build_runner build --delete-conflicting-outputs

  locale-gen:
    description: Generate localization
    packageFilters:
      flutter: true
      scope: app_translations
    exec: dart run slang

  build-apk:
    description: Build Android APK (production)
    packageFilters:
      flutter: true
      scope: app_core
    exec: flutter build apk -t lib/main_production.dart --flavor prod

  build-bundle:
    description: Build Android App Bundle
    packageFilters:
      flutter: true
      scope: app_core
    exec: flutter build appbundle -t lib/main_production.dart

  build-ipa:
    description: Build iOS IPA (production)
    packageFilters:
      flutter: true
      scope: app_core
    exec: flutter build ipa -t lib/main_production.dart --flavor prod

  go-ios-go:
    description: Reset iOS Pods & reinstall
    packageFilters:
      scope: app_core
    run: |
      cd ios
      rm -rf Pods Podfile.lock
      pod install --repo-update

  widgetbook-gen:
    description: Generate Widgetbook files
    packageFilters:
      scope: widgetbook_workspace
    exec: dart run build_runner build --delete-conflicting-outputs

  format:
    description: Format & fix Dart code
    run: |
      dart format . --line-length 70 --output=none
      dart fix --apply --code=require_trailing_commas
    exec:
      concurrency: 10
