name: boilerplate-application-melos

packages:
  - packages/*

scripts:
  analyze:
    run: |
      melos exec -c 5 -- \
        dart analyze . --fatal-infos

  build-runner:
    description: Generate environment configuration, assets and other code generation
    packageFilters:
      flutter: true
      dirExists: lib
      scope: app_core
    run: melos exec dart run build_runner clean && melos exec dart run build_runner build -d

  locale-gen:
    description: Generate localization
    packageFilters:
      flutter: true
      dirExists: lib
      scope: app_core
    exec: dart run easy_localization:generate -f keys -o locale_keys.g.dart -O ./lib/gen -S assets/l10n

  build-apk:
    description: Builds the APK File
    packageFilters:
      flutter: true
      dirExists: lib
      scope: app_core
    exec: flutter build apk -t lib/main_development.dart

  format:
    description: Formats the files
    exec: dart run lint_staged

  abc:
    description: Formats the files
    exec: dart format . --line-length 120 --set-exit-if-changed
