name: boilerplate-application-melos

packages:
  - packages/**
  - apps/**

scripts:
  analyze:
    run: |
      melos exec -c 10 -- \
        dart analyze . --fatal-infos

  build-runner:
    description: Generate environment configuration, Routes files and other code generation
    packageFilters:
      flutter: true
      dirExists: lib
      scope: app_core
    run: melos exec dart run build_runner clean && melos exec dart run build_runner build -d

  asset-gen:
    description: Generate assets
    packageFilters:
      flutter: true
      dirExists: lib
      scope: app_ui
    run: melos exec dart run build_runner build -d

  locale-gen:
    description: Generate localization
    packageFilters:
      flutter: true
      dirExists: lib
      scope: app_translations
    exec: dart run slang

  build-apk:
    description: Builds the APK File
    packageFilters:
      flutter: true
      dirExists: lib
      scope: app_core
    exec: flutter build apk -t lib/main_production.dart --flavor production

  build-bundle:
    description: Builds the Bundle File
    packageFilters:
      scope: app_core
    exec: flutter build appbundle -t lib/main_production.dart

  build-ipa:
    description: Builds the ipa for ios
    packageFilters:
      scope: app_core
    exec: flutter build ipa -t lib/main_production.dart --flavor prod

  go-ios-go:
    description: Removes Podfile.lock & Pods Directory & Installs PodFile
    packageFilters:
      scope: app_core
    exec: cd ios && rm -rf Pods && rm -rf Podfile.lock && pod install --repo-update

  format:
    description: Formats the files
    run: |
      melos exec -c 10 -- \
        dart format . --line-length 100 --output=none && dart fix --apply --code=require_trailing_commas
