include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    always_specify_types: false
    avoid_print: true
    always_use_package_imports: true
    package_api_docs: true

analyzer:
  errors:
    prefer_single_quotes: warning
    unawaited_futures: warning
    unused_import: warning
    unrelated_type_equality_checks: error
    annotate_overrides: error
    avoid_print: error
    avoid_relative_lib_imports: error
    prefer_const_constructors: error
    prefer_final_in_for_each: error
    unnecessary_breaks: error
    unnecessary_const: error
    use_super_parameters: error
    missing_return: error
    missing_required_param: error
    invalid_assignment: ignore
    strict_raw_type: ignore
    directives_ordering: ignore
    inference_failure_on_instance_creation: ignore
    avoid_bool_literals_in_conditional_expressions: ignore
    depend_on_referenced_packages: ignore
    sort_pub_dependencies: ignore
    dead_code: info
    todo: info
    invalid_annotation_target: ignore

  exclude:
    # - "**_model.dart"
    - "**.g.dart"
    - "**.freezed.dart"
    - "**.config.dart"
    - "**.chopper.dart"
    - "**.mocks.dart"
    - lib/app/generated/**.dart
    - lib/app/generated/**
    - lib/**/generated_plugin_registrant.dart
    - bricks/**

    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
